In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("Data.csv")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(X)
# print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


### Spliting data into training and testing

In [9]:
# Import necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [10]:
# Load the Iris dataset
iris = load_iris()
# iris.feature_names

In [11]:
# Separate features and target
# Features
X = iris.data
# Target
y = iris.target

In [12]:
# Split the dataset into an 80-20 training-test set
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [13]:
print(X_train.size)

480


In [14]:
print(X_test.size)

120


In [15]:
print(y_train.size)

120


In [16]:
print(y_test.size)


30


In [19]:
# Apply feature scaling on the training and test sets
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
# Print the scaled training and test sets
print(X_train)
print(X_test)

[[ 0.31553662 -0.04578885  0.44767531  0.23380268]
 [ 2.2449325  -0.04578885  1.29769171  1.39742892]
 [-0.2873996  -1.24028061  0.05100098 -0.15407273]
 [ 0.67729835 -0.52358555  1.01435291  1.13884531]
 [-0.04622511 -0.52358555  0.73101411  1.52672073]
 [-0.64916132  1.62649961 -1.30902526 -1.31769898]
 [-0.40798684 -1.71807731  0.10766874  0.10451088]
 [-0.76974857  0.90980456 -1.36569302 -1.31769898]
 [ 0.79788559 -0.52358555  0.44767531  0.36309449]
 [ 1.03906007 -1.24028061  1.12768843  0.7509699 ]
 [ 1.15964732 -0.04578885  0.95768515  1.13884531]
 [-0.89033581  1.14870291 -1.36569302 -1.18840717]
 [ 0.19494938 -1.95697567  0.67434635  0.36309449]
 [ 0.5567111  -0.2846872   1.01435291  0.7509699 ]
 [ 0.91847283 -0.2846872   0.44767531  0.10451088]
 [ 2.2449325  -1.00138226  1.75103379  1.39742892]
 [-0.16681235  1.86539796 -1.19568974 -1.18840717]
 [-1.01092305  1.38760126 -1.36569302 -1.31769898]
 [-1.25209754 -0.04578885 -1.36569302 -1.18840717]
 [-0.76974857 -0.76248391  0.05

In [25]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Wine Quality Red dataset
dataset = pd.read_csv('./winequality-red.csv')

# Separate features and target
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

# Split the dataset into an 80-20 training-test set
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

# Create an instance of the StandardScaler class
sc = StandardScaler()

# Fit the StandardScaler on the features from the training set and transform it
X_train = sc.fit_transform(X_train)

# Apply the transform to the test set
X_test = sc.transform(X_test)

# Print the scaled training and test datasets
print(X_train)
print(X_test)

[[-0.73307913  0.6648928  -1.25704443 ...  0.98846046  0.0630946
  -0.87223395]
 [ 1.06774091 -0.62346154  1.52314768 ... -1.7535127  -0.17390392
  -0.77978452]
 [-1.74604041 -1.07158479 -1.35814232 ...  2.32756363  0.77409018
   3.28799021]
 ...
 [-0.95818164  1.08500835 -0.90320179 ...  0.22325865 -1.00339876
   0.32960859]
 [-0.62052788  0.55286199 -1.35814232 ...  0.35079228 -0.47015208
  -1.33448108]
 [ 0.44870902 -0.73549236  1.16930505 ... -0.6694768   0.18159387
   1.90124882]]
[[ 0.27988214 -0.67947695  1.87699031 ...  1.43482818  0.00384497
   0.05226031]
 [ 0.22360652  0.55286199  0.05722821 ... -0.35064271 -0.17390392
  -0.22508797]
 [ 1.18029216 -1.07158479  1.57369663 ... -0.79701044  0.2408435
   0.79185571]
 ...
 [-0.67680351  0.77692361 -1.35814232 ...  0.79716001 -0.7071506
  -0.96468337]
 [-1.18328414 -0.79150776  0.81546242 ...  0.86092682  1.24808723
   0.69940629]
 [ 1.4616703  -1.18361561  1.27040294 ... -0.22310908  0.65559092
   0.97675456]]
